[package]
name = "hello-world-fuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = { version = "0.11" }
clap = { version = "3.2", features = ["derive"] }
libc = { version = "0.2" }